;; The checkout form. Its values, touched fields, and submission state are local; the
;; page decides what happens with a placed order.
;;
;; A field shows its error after the field loses focus, or after a submit attempt.
(define-module (views checkout-form)
  #:pure
  #:export (checkout-form)
  #:use-module (scheme base)
  #:use-module ((roost dom) #:prefix h/)
  #:use-module ((roost props) #:select (props let-props))
  #:use-module ((roost hiccup) #:select (component))
  #:use-module ((roost hooks) #:select (use-state))
  #:use-module ((roost js) #:prefix js/)
  #:use-module (store products)
  #:use-module (store text)
  #:use-module (store order-form)
  #:use-module (views controls))

;; Card numbers are kept as digits grouped by four, whatever is typed or pasted.
(define (normalize key value)
  (if (eq? key 'card)
      (group-card-number (digits-only value))
      value))

(define (checkout-form attributes)
  (let-props attributes (can-order? submitting? on-submit)
    (let-values (((form set-form!) (use-state initial-form))
                 ((touched set-touched!) (use-state '()))
                 ((billing-same? set-billing-same!) (use-state #t))
                 ((attempted? set-attempted!) (use-state #f)))
      (let ((errors (validate form billing-same?)))
        (define (error-for key)
          (and (or attempted? (memq key touched))
               (let ((entry (assq key errors))) (and entry (cdr entry)))))

        (define (field key label . options)
          (component text-field
                     (apply props
                            #:key (symbol->string key) #:label label #:name (symbol->string key)
                            #:value (form-ref form key)
                            #:on-change (lambda (value)
                                          (set-form! (lambda (f) (form-set f key (normalize key value)))))
                            #:on-blur (lambda ()
                                        (set-touched! (lambda (t) (if (memq key t) t (cons key t)))))
                            #:error (error-for key)
                            options)))

        (define (submit event)
          (js/method event "preventDefault")
          (set-attempted! #t)
          (when (and can-order? (null? errors))
            (on-submit form)))

        (h/form
         (props #:class "checkout" #:no-validate #t #:on-submit submit)
         (h/h2 "Checkout")
         (h/fieldset
          (h/legend "Contact")
          (field 'email "Email" #:type "email" #:placeholder "you@example.com")
          (field 'phone "Phone (optional)" #:type "tel"))
         (h/fieldset
          (h/legend "Shipping address")
          (field 'name "Full name")
          (field 'street "Street")
          (h/div (props #:class "row")
                 (field 'city "City")
                 (field 'postal "Postal code"))
          (h/label (props #:class "field")
                   (h/span "Country")
                   (h/select (props #:name "country" #:value (form-ref form 'country)
                                    #:on-change (lambda (event)
                                                  (let ((value (event-value event)))
                                                    (set-form! (lambda (f) (form-set f 'country value))))))
                             (map (lambda (c) (h/option (props #:key c #:value c) c)) countries))))
         (h/label (props #:class "check")
                  (h/input (props #:type "checkbox" #:checked billing-same?
                                  #:on-change (lambda (event) (set-billing-same! (event-checked event)))))
                  "Billing address is the same as shipping")
         (and (not billing-same?)
              (h/fieldset
               (h/legend "Billing address")
               (field 'billing-name "Full name")
               (field 'billing-street "Street")
               (h/div (props #:class "row")
                      (field 'billing-city "City")
                      (field 'billing-postal "Postal code"))))
         (h/fieldset
          (h/legend "Payment")
          (field 'card "Card number" #:placeholder "1234 5678 9012 3456")
          (h/div (props #:class "row")
                 (field 'expiry "Expiry" #:placeholder "MM/YY")
                 (field 'cvc "CVC")))
         (and attempted? (pair? errors)
              (h/div (props #:class "summary" #:role "alert")
                     (h/strong (length errors) (if (= 1 (length errors)) " field needs" " fields need")
                               " attention")
                     (h/ul (map (lambda (e) (h/li (props #:key (symbol->string (car e))) (cdr e)))
                                errors))))
         (and attempted? (not can-order?)
              (h/p (props #:class "error") "Add something to your cart first."))
         (h/button (props #:type "submit" #:class "primary" #:disabled submitting?)
                   (if submitting? "Placing order…" "Place order")))))))
